export const projects = [
  {
    id: 1,
    name: "SCHWARZER RITTER - E-COMMERCE WEBSITE",
    timeLine: "07-2023 - 08-2023",
    desc: "Developed a comprehensive online e-commerce platform that enables users to browse, select, purchase, and manage products seamlessly",
    webUrl: "https://sales.schwarzerritter.tech/",
    githubUrlFE: "https://github.com/SatomiJin/Web-sales",
    githubUrlBE: "https://github.com/SatomiJin/sales-backend",
    image: "https://raw.githubusercontent.com/SatomiJin/cv-images/main/schwarzer-ritter.png",
    tech: ["react", "node", "scss", "bootstrap", "postgresql"],
  },
  {
    id: 2,
    name: "WEBSITE BOOKING CARE",
    timeLine: "08-2023 - 09-2023",
    desc: "Designed and developed an online platform called Booking Care that allows users to schedule appointments with healthcare professionals for medical consultations and services.",
    webUrl: "",
    githubUrlFE: "https://github.com/SatomiJin/KoutaCare-Frontend",
    githubUrlBE: "https://github.com/SatomiJin/KoutaCare-backend",
    image: "",
    tech: ["React", "Node", "Redux", "Bootstrap", "postgresql"],
  },
  {
    id: 3,
    name: "E-LEARNING WEBSITE",
    timeLine: "02-2022 - 03-2022",
    desc: "Designed and developed an interactive e-learning platform to provide engaging educational content to learners across various subjects and levels.",
    webUrl: "",
    githubUrlFE: "https://github.com/SatomiJin/WebLearning",
    githubUrlBE: "",
    image: "https://raw.githubusercontent.com/SatomiJin/cv-images/main/Elearning.png",
    tech: ["HTML", "CSS", "PHP", "MySQL"],
  },
  {
    id: 4,
    name: "E-COMMERCE WEBSITE - V2",
    timeLine: "01/11/2023 - 15/12/2023",
    desc: " Developed a comprehensive online e-commerce platform that enables users to browse,select, purchase, and manage products seamlessly.",
    webUrl: "https://shop.satomijin.id.vn/",
    githubUrlFE: "https://github.com/SatomiJin/Ecommerce-v2-FE",
    githubUrlBE: "https://github.com/SatomiJin/Ecommerce-v2-BE",
    image:
      "https://raw.githubusercontent.com/SatomiJin/cv-images/main/423472581_749376933841060_2595966124996006158_n.png",
    tech: ["HTML", "CSS", "PHP", "MySQL"],
  },
];
